---
title: "Data Science Salaries"
author: "Trillyon Earl"
date: "2025-03-01"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!-- Libraries & Setup -->
```{r libs}
library(MASS)
library(car)
library(nnet)
library(dplyr)
```

<!-- Data Clean-Up -->
```{r cleanup}
loan <- read.csv("./loan_data.csv")
loan <- as_tibble(loan)
loan <- loan |> mutate(
  person_gender = factor(person_gender, ordered = FALSE, levels = c("female", "male")),
  person_education = factor(person_education, ordered = TRUE, levels = c("High School", "Associate", "Bachelor", "Master", "Doctorate")),
  person_home_ownership = factor(person_home_ownership, ordered = FALSE, c("RENT", "OWN", "MORTGAGE", "OTHER")),
  loan_intent = factor(loan_intent, ordered = FALSE, c("PERSONAL", "MEDICAL", "EDUCATION", "VENTURE", "HOMEIMPROVEMENT", "DEBTCONSOLIDATION"))
)
loan

#Variable naming and indicator creation
train <- loan[1:36000,]
test <- loan[36001:45000,]
age <- train$person_age; gender <- train$person_gender; education <- train$person_education; income <- train$person_income; exp <- train$person_emp_exp; HO <- train$person_home_ownership; loan_amnt <- train$loan_amnt; loan_intent <- train$loan_intent; loan_int_rate <- train$loan_int_rate; loan_percent_income <- train$loan_percent_income; cred_hist_length <- train$cb_person_cred_hist_length; credit_score <- train$credit_score; prev_defaults <- train$previous_loan_defaults_on_file; status <- train$loan_status

#Gender indicators (male is baseline)
female <- ifelse(gender == "female", 1, 0)

#Education indicators (High School is Baseline)
associate <- ifelse(education == "Associate", 1, 0)
bachelor <- ifelse(education == "Bachelor", 1, 0)
master <- ifelse(education == "Master", 1, 0)
phd <- ifelse(education == "Doctorate", 1, 0)

#Home ownership indicators (OTHER is baseline)
rent <- ifelse(HO == "RENT", 1, 0)
mortgage <- ifelse(HO == "MORTGAGE", 1, 0)
own <- ifelse(HO == "OWN", 1, 0)

#Loan intent indicators (PERSONAL is baseline)
education <- ifelse(loan_intent == "EDUCATION", 1, 0)
medical <- ifelse(loan_intent == "MEDICAL", 1, 0)
venture <- ifelse(loan_intent == "VENTURE", 1, 0)
homeimprov <- ifelse(loan_intent == "HOMEIMPROVEMENT", 1, 0)
debtconsol <- ifelse(loan_intent == "DEBTCONSOLIDATION", 1, 0)

#Previous loan defaults on file indicator (No is baselines)
yesdefault <- ifelse(prev_defaults == "Yes", 1, 0)
```

## Abstract
<!-- Explain The Data -->
 - Explain what the data columns are, what the different values of each column.
 - Explain what data we decided to exclude before any training.
 
## Objective
<!-- State the objective of this project -->
  - i.e the objective is seek value information out of a specific dataset using regressional techniques.
  
## Methods
<!-- What type of regession techniques did we use? -->
  - i.e nominal / logistic / ordinal / linear / multilinear
<!-- What type of variable selection methods did we use? -->
  
<!-- What type of model selection method did we use? -->

## Analysis
  <!-- Analysis Introduction -->
  
## Conclusion
  - 

